### ISSUE TITLE
Running in a loop: No module named 'numpy.core._multiarray_umath'

### ISSUE THREAD

**Issue by mr-september** [medmaca/PGCNA#4]
As discussed in an earlier issue, I need to run PGCNA in a loop, so each input file produces 1 output network which does not get joined up with the others.

This is the script I've come up with:
```
# pip install numpy
# pip install scipy
# pip install h5py

import os
import pgcna2 #pgcna2.py

# Set up paths
parentDirectory = os.path.abspath(os.path.join(os.getcwd(), os.pardir))
inputDirectory = os.path.join(parentDirectory, 'Inputs')
outputDirectory = os.path.join(parentDirectory, 'Outputs/PGCNA')

# The main command
#./pgcna2.py -w <workFolderPath> -d <expressionFilesFolderPath>

for file in os.listdir(inputDirectory):
    filename = os.fsdecode(file)
    # DEs files are almost all zeros, as intended
    if filename.startswith("CoEx_") and filename.endswith(".txt") and "DEs" not in filename:
        # Rewrite/update #FileInfo.txt
        with open(os.path.join(inputDirectory, "#FileInfo.txt"), "w") as file:
            file.write("Filename\tHeaderLines\n" + filename + "\t1")
            file.close

        # Main Code
        # os.system("python3 pgcna2 -w "+ outputDirectory + " -d "inputDirectory + " -f 1 --usePearson --noLeidenalg")
        os.system("python3 pgcna2 -w ", outputDirectory, " -d ", inputDirectory, " -f 1 --usePearson --noLeidenalg")
    else:
        continue
```
And the error code:
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/usr/lib/python3/dist-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/usr/lib/python3/dist-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/<redacted>/Python/PGCNA/PGCNA2/Loop PGCNA2.py", line 6, in <module>
    import pgcna2
  File "/media/<redacted>/Python/PGCNA/PGCNA2/pgcna2.py", line 43, in <module>
    import numpy as np
  File "/usr/lib/python3/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/lib/python3/dist-packages/numpy/core/__init__.py", line 50, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.9 from "/usr/bin/python3.9"
  * The NumPy version is: "1.18.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'


Process finished with exit code 1
```

The strange thing is, manually running `./pgcna2.py -w <workFolderPath> -d <expressionFilesFolderPath>` with hardcoded paths work just fine, but this error doesn't sound like it's about bad pathing. So the fixes mentioned in other threads don't apply, either (i tried a few anyway, mostly about re-installing numpy).

Do you know how this can be solved? Is the way I'm writing the loop bad?

**Comment by medmaca** [comment]
Quick question, on line 6 you're importing pgcna2, what happens if you comment out that line?

**Comment by mr-september** [comment]
```
Traceback (most recent call last):
  File "/media/<redacted>/Python/PGCNA/PGCNA2/LoopPGCNA2.py", line 18, in <module>
    for file in os.listdir(inputDirectory):
FileNotFoundError: [Errno 2] No such file or directory: '/media/<redacted>/Python/PGCNA/Inputs'
```

I think it may be a systems issue on my end, though, someone else was able to run the code as-is on their laptop. Closing this for now.
